### ISSUE TITLE
Only Reading First SteamID

### ISSUE THREAD

**Issue by Shaneajm** [marius137/steam-ban-checker#1]
Hey! I'm running into a bug where it only reads the first SteamID, but reads it for as many ID's there are in the list. Example below:

> #paste accounts one per line here
> STEAM_1:0:521351800
> STEAM_1:1:105431960
> STEAM_1:0:589415412
> STEAM_1:0:592072090
> STEAM_1:1:591410403
> STEAM_1:0:569378248
> STEAM_1:0:591184679
> STEAM_1:1:569831920
> STEAM_1:0:573051941
> STEAM_1:0:568428787
> etc....

## Console Response

> lll (76561197983360497)
> VAC Bans: 0 GameBans: 0
> 
> lll (76561197983360497)
> VAC Bans: 0 GameBans: 0
> 
> lll (76561197983360497)
> VAC Bans: 0 GameBans: 0
> 
> lll (76561197983360497)
> VAC Bans: 0 GameBans: 0
> 
> lll (76561197983360497)
> VAC Bans: 0 GameBans: 0
> 
> lll (76561197983360497)
> VAC Bans: 0 GameBans: 0
> 
> lll (76561197983360497)
> VAC Bans: 0 GameBans: 0
> 
> lll (76561197983360497)
> VAC Bans: 0 GameBans: 0
> etc....

Any ideas as to a fix? This is just the tool I was looking for :)

**Comment by marius137** [comment]
I will take a look on Monday

**Comment by marius137** [comment]
you are using steamIDs, the tool only supports steamID64, customURL and links to profiles.
I'll look into adding support for steamIDs too.
